### ISSUE TITLE
Option to not automatically append a / to the end of URLs

### ISSUE THREAD

**Issue by nyejon** [florimondmanca/asgi-sitemaps#6]
Hey!

It would be great to have an option to not automatically append the slash to the end of the URL.

**Comment by florimondmanca** [comment]
Heya,

Sure, sounds legit. Happy to review any PRs towards that, though keep in mind I'm possibly considering changing the usage and API, see #4.

**Comment by nyejon** [comment]
That's a great idea. Should be a lot more dynamic to have it automatically update.

Sure, will you reuse this:
 child_urls = [_normalize(urljoin(url, href)) for href in hrefs]

I guess it's just adding a flag whether or not to normalize the URL.

**Comment by florimondmanca** [comment]
Hi @nyejon,

Just merged #4, as of 0.3.0 (yet to be released) the new API will leave you 100% in control of URL paths, so you'll be able to decide if you want trailing slashes or not. :-)

**Comment by nyejon** [comment]
Great :) Will give it a test
